import type { Metadata } from "next";
import { Red_Hat_Display, Red_Hat_Text } from "next/font/google";
import "../globals.css";
import Footer from "../components/layout/Footer";
import InnerHeader from "../components/reusable/InnerHeader";
import { Toaster } from "react-hot-toast";

const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["400", "500", "700"], 
  variable: "--font-red-hat-display", 
});

const redHatText = Red_Hat_Text({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-red-hat-text",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${redHatDisplay.variable} ${redHatText.variable} antialiased`}
      >
        <InnerHeader />
        {children}
        <Toaster position="top-right" />
        <Footer />
      </body>
    </html>
  );
}
